// Generated by svd2swift.

import MMIO

/// FLASH
let flash = FLASH(unsafeAddress: 0x4002_3c00)

/// General-purpose I/Os
let gpioa = GPIOA(unsafeAddress: 0x4002_0000)

/// General-purpose I/Os
let gpiob = GPIOB(unsafeAddress: 0x4002_0400)

/// General-purpose I/Os
let gpioc = GPIOC(unsafeAddress: 0x4002_0800)

/// General-purpose I/Os
let gpiod = GPIOD(unsafeAddress: 0x4002_0c00)

/// General-purpose I/Os
let gpioe = GPIOE(unsafeAddress: 0x4002_1000)

/// General-purpose I/Os
let gpiof = GPIOF(unsafeAddress: 0x4002_1400)

/// General-purpose I/Os
let gpiog = GPIOG(unsafeAddress: 0x4002_1800)

/// General-purpose I/Os
let gpioh = GPIOH(unsafeAddress: 0x4002_1c00)

/// General-purpose I/Os
let gpioi = GPIOI(unsafeAddress: 0x4002_2000)

/// General-purpose I/Os
let gpioj = GPIOJ(unsafeAddress: 0x4002_2400)

/// General-purpose I/Os
let gpiok = GPIOK(unsafeAddress: 0x4002_2800)

/// LCD-TFT Controller
let ltdc = LTDC(unsafeAddress: 0x4001_6800)

/// Reset and clock control
let rcc = RCC(unsafeAddress: 0x4002_3800)
